server:
  port: 8001

spring:
  application:
    name: IBMP-Client
  profiles:
    include: common
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  redis:
    redisson:
      config: |
        threads: 4
        nettyThreads: 8
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        singleServerConfig:
          address: redis://172.27.79.196:6379
          password: redis
          subscriptionConnectionPoolSize: 4
          connectionMinimumIdleSize: 1
          connectionPoolSize: 4


app:
  family: ibmp
  name: client
  url:
    version: v1
  adaptors:
    services:
      server:
        uri: http://localhost:8000
        urls:
          customer: /ibmp/v1/server/customer