[workspace]
resolver = "2"

members = [
    "gui/egui_demo",
    "gui/druid_demo",
    "gui/iced_demo",
    "playground",
    "practice/minegrep",
    "practice/rust_model_example",
    "practice/comprehensive_rust"
]
