[package]
name = "egui-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
eframe = {version = "0.22.0", features = ["__screenshot"]}
rfd = "0.11.4"
egui_demo_lib = "0.22.0"
